### ISSUE TITLE
React

### ISSUE THREAD

**Issue by roberbnd** [jaredgorski/SpaceCamp#1]
![newcolor](https://user-images.githubusercontent.com/4907027/58841281-c1d39f80-862e-11e9-8e3f-8374e15312e9.png)
How can I help to improve the colorscheme with react?, the left is this colorscheme and the right is vscode colorscheme

**Comment by jaredgorski** [comment]
Didn’t get a chance to test with React yet! Great catch though, seems the JSX aspects don’t get styled by the HTML syntax definitions. I’ll have to do some research (probably checking other Vim color scheme repos, like the vscode one) to see what syntax group IDs Vim uses to color JSX/React code.

That said, if you fork and add a JSX or React section to the file, I’ll happily approve any PR that improves this color scheme. The file is constructed in such a way that adding sections for specific languages should be rather intuitive. The colors are defined in variables that can be added to function calls which construct and execute the necessary `hi` definitions.

I’ll also explore this in my free time if you don’t have time to contribute, so no pressure.

Thanks for using and creating the issue! All contributions are greatly appreciated.

**Comment by roberbnd** [comment]
just for now I want to leave the note: it's works vscode scheme because I use https://github.com/neoclide/vim-jsx-improve and some way that right now I don't understand  they work together
