### ISSUE TITLE
No highlighting with vim-buftabline

### ISSUE THREAD

**Issue by oxysoft** [jaredgorski/SpaceCamp#12]
The active buffer is not highlighted, making it hard to visually navigate the bar with prev/next shortcuts.

**Comment by jaredgorski** [comment]
I have not used this plugin personally, but I'm open to adding support. According to the documentation, support can be added via the special color groups listed here: https://github.com/ap/vim-buftabline/blob/master/doc/buftabline.txt#L112-L133

If you'd like to add this locally, I can explain to you how to add color groups to your `.vim/colors/spacecamp.vim` file (or equivalent file). Then, if you would like to send a PR, I'll consider merging it.. just as long as I think this library is widely used enough to support 😄
