### ISSUE TITLE
[Enhancement] Add FoldColumn & SignColumn highlight

### ISSUE THREAD

**Issue by sophiabrandt** [jaredgorski/SpaceCamp#14]
Thank you for creating this color theme.

Would it be possible to set `highlight` for `FoldColumn` as well?
At the moment, my Vim looks like in this [issue](https://github.com/haishanh/night-owl.vim/issues/8) with a light grey and cyan highlights.

That should be fixable by setting `FoldColumn`, similar to [here](https://github.com/haishanh/night-owl.vim/commit/df79108278a68fa1792f9f32a96b9dada825ff3f).

So adding something like this that fits into your vision of the colorscheme?
```
call <sid>hi('FoldColumn', s:spaceBlack, s:none, 'none')
```
It would also be wonderful if you set the `SignColumn` as well. The sign column is used for plugins like `vim-gitgutter`.
```
call <sid>hi('SignColumn', s:spaceBlack, s:none, 'none')
```

I hope it's not too much of a bother. Thank you.

**Comment by jaredgorski** [comment]
@sophiabrandt thanks so much for bringing this up! I haven't seen this happen personally on my setup (I use gitgutter all day), but I want to make sure this works properly everywhere. I appreciate the links and explanation. Let me see what I can do.

Do you have any suggestions for fg/bg colors? Otherwise, I think I'll just go with the same fg/bg as the line numbers.

**Comment by sophiabrandt** [comment]
Wow, thanks for your friendly reply. :100: 

I think the best option would be to set the colors as unobtrusive as possible, so something like the line numbers would be fine.
I saw that in the issue I mentioned above, the author opted for a slightly darker color than `LineNr` to distinguish the columns. So that would be an option as well.

I personally would prefer the second option, but I don't know how much work that is for you.

Thank you for your time!

**Comment by jaredgorski** [comment]
@sophiabrandt - I experimented with it this morning and realized that `foldcolumn` is the culprit. I found this style I like, but there are other ways to do it so I want to get your preference. What do you think?

<img width="630" alt="Screen Shot 2020-05-13 at 9 48 43 AM" src="https://user-images.githubusercontent.com/36674760/81841343-22d24b80-94ff-11ea-843e-72e718cd499c.png">

Regarding signcolumn, oddly enough I can't see the difference when adding styles for it in the theme, even though I have `signcolumn=yes` in my config. I'm on vim 8.2. If you're not opposed, I'll just blindly set this to match whatever we decide for the foldcolumn.

Let me know if you like what I did in the image above, or if you think it would be nicer a different way. Thanks again!

**Comment by sophiabrandt** [comment]
@jaredgorski Yes, that looks sweet! I think it integrates well with the theme, but still is distinctive enough! Thank you! :1st_place_medal:

**Comment by jaredgorski** [comment]
Thanks again @sophiabrandt!

Closed in https://github.com/jaredgorski/SpaceCamp/commit/3720065aa9d854c12e813786849cf24bc1225816
