### ISSUE TITLE
Question on Font

### ISSUE THREAD

**Issue by dinogomez** [jaredgorski/SpaceCamp#15]
What font is used here? Its absolutely gorgeous 
![image](https://user-images.githubusercontent.com/41871666/93853420-6bd4b080-fce6-11ea-8a09-a32e2498a3e2.png)

**Comment by jaredgorski** [comment]
Hi @dinogomez, great question.

I actually captured this screenshot from http://vimcolors.com/. Upon inspecting in the developer tools, it appears to be "Menlo"

It's available by default on macOS Xcode and terminal, and there's a TTF version available here: https://github.com/hbin/top-programming-fonts/blob/master/Menlo-Regular.ttf

P.S.: sorry for the delay, was on vacation

**Comment by dinogomez** [comment]
Hi @jaredgorski 

Thanks a lot for the response. I was searching for this, really love the theme and thanks for the TTF version!
