### ISSUE TITLE
[Question] [README.md] Why are the two colors different?

### ISSUE THREAD

**Issue by cutbypham** [jaredgorski/SpaceCamp#17]
![image](https://user-images.githubusercontent.com/40050527/112974463-b430c780-917c-11eb-8cf5-c026ee9b627f.png)

**Comment by jaredgorski** [comment]
The colors on the left are for 16 color terminals, but the colors on the right are the basic colors in the default version of the theme. In personal experimentation, I found the 16 colors listed on the left most comfortable in my MacOS Terminal settings, but they're just a guide. There's no `orange` on 16 color terminals for example, so I opted for a brighter shade of `red`, and kept `#FF0000` as `bright red`. I also appreciated slightly less contrast between the background and foreground, hence the slight shift from `#262626` to `#282828`. Your mileage may vary, however.

I haven't made any particular set of colors "official", especially considering that the `lite` theme deviates from these colors in some ways.
