### ISSUE TITLE
Transaprent background theme variant

### ISSUE THREAD

**Issue by BANOnotIT** [jaredgorski/SpaceCamp#22]
I usually use fullscreen terminal so I really like it's feature to make background transparent so I can e.g. see commands behind terminal window to enter in terminal. And I found it useful to disable background color in vim theme to support this use case.

Here's my config:
```vim
colorscheme spacecamp
hi Normal guibg=#121212 ctermbg=NONE
hi! link EndOfBuffer Normal
```

**Comment by jaredgorski** [comment]
Thanks for sending! I'll have to think about this, since the bg color is there on purpose (I'm not a transparent terminal person). I'm leaning towards "this should be in a fork", but I may be missing some key detail that lets us have both.

**Comment by BANOnotIT** [comment]
I think that people looking for the solution might find this issue useful.
