### ISSUE TITLE
SpaceCamp VSCode Approval Request

### ISSUE THREAD

**Issue by dinogomez** [jaredgorski/SpaceCamp#27]
Hey Jared, 

I've been a fan of the theme when I first saw it, even sent an email asking for the font used dating back to 2020. I eventually had the time to make a port towards VSCode while also adding some of my preferences but still keeping the SpaceCamp theme in a whole.

![image](https://github.com/jaredgorski/SpaceCamp/assets/41871666/f9ca7286-53e1-4549-9ca2-95cbcb753359)

I'm asking for your approval first before submitting it to the VSCode Marketplace as well as start a new repository.

The extension is found here [LINK](https://marketplace.visualstudio.com/items?itemName=PaulGomez.spacecamp)

Looking forward to your response.

Thanks,
Dino

**Comment by jaredgorski** [comment]
Hey @dinogomez,

I'm glad you like the colors!

You technically don't need my approval at all ([MIT license](https://github.com/jaredgorski/SpaceCamp/blob/master/LICENSE)) but you have it anyway. Feel free to do whatever you like with all or part of the colors, ideas, or whatever you see fit.

Best,
Jared
